name: Commenter

on:
  pull_request_target:

  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed

permissions:
  contents: read

jobs:
  comment-test:
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request_target' }}
    steps:
      - name: Comment PR - How to test
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: How to test
          message: |
            ## How to test

            ```sh
            git clone -b ${{ github.head_ref }} https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
            cd hexo
            npm install
            npm test
            ```

  comment-flamegraph:
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
      actions: read # get artifact
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'workflow_run' }}
    env:
      comment_file_pattern: ".tmp-comment-flamegraph-*.md"
      comment_result: ".tmp-comment-flamegraph.md"
    steps:
      - name: get PR number
        id: get_pr_number
        env:
          pr_array: ${{toJSON(github.event.workflow_run.pull_requests)}}
        uses: actions/github-script@v6
        with:
          script: |
            const pr_array=JSON.parse(process.env.pr_array);
            if(pr_array.length===1){
              core.setOutput('pr_number', pr_array[0].number);
            }else{
              core.setFailed(`Fail to get PR number!`);
            }

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          run-id: ${{toJSON(github.event.workflow_run.id)}}
          pattern: "comment-pr${{steps.get_pr_number.outputs.pr_number}}-node*"
          merge-multiple: true

      - name: combime comment
        run: |
          echo "## flamegraph" > ${{env.comment_result}}
          echo "" >> ${{env.comment_result}}
          cat ${{env.comment_file_pattern}} >> ${{env.comment_result}}

      - name: Comment PR - flamegraph
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          number: ${{steps.get_pr_number.outputs.pr_number}}
          header: flamegraph
          path: ${{env.comment_result}}
